FROM nubificus_base_build

USER root

# Install rust using rustup
ENV RUSTUP_HOME=/opt/rust CARGO_HOME=/opt/cargo PATH=/opt/cargo/bin:$PATH
RUN wget --https-only --secure-protocol=TLSv1_2 -O- https://sh.rustup.rs | sh /dev/stdin -y
RUN chmod a+w /opt/cargo
RUN chmod a+w /opt/rust

USER runner
ENTRYPOINT ["/entrypoint.sh"]
