name: build-arch
on:
  workflow_dispatch:
    inputs:
      matrix:
        required: true
        type: string

  workflow_call:
    inputs:
      matrix:
        required: true
        type: string



jobs:
  manifest:
    runs-on: [ self-hosted, lite ]
    #needs: [ build, prepare ]
    strategy:
      matrix:
           ${{ fromJson(inputs.matrix) }}
      fail-fast: false

    steps:
    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        #username: ${{ github.actor }}
        username: ${{ secrets.HARBOR_USER }}
        #password: ${{ secrets.GITHUB_TOKEN }}
        password: ${{ secrets.HARBOR_SECRET }}


    - name: Manifest images under one label
      shell: bash {0}
      run: |
        echo "${{ matrix.dockerfile }}"
        #ARM=$( echo "${{ matrix.dockerfile }}" | sed s/Dockerfile\.// )-"aarch64"
        #X86=$( echo "${{ matrix.dockerfile }}" | sed s/Dockerfile\.// )-"x86_64"
        GEN=$( echo "${{ matrix.dockerfile }}" | sed s/Dockerfile\.// )
        #echo $ARM
        #echo $X86
        echo $GEN
        docker manifest rm ${{ env.REGISTRY }}/gh-actions-runner-$GEN:generic || true
        docker manifest create ${{ env.REGISTRY }}/gh-actions-runner-$GEN:generic \
            --amend ${{ env.REGISTRY }}/gh-actions-runner-$GEN:aarch64 \
            --amend ${{ env.REGISTRY }}/gh-actions-runner-$GEN:x86_64
        #docker manifest push ${{ env.REGISTRY }}/gh-actions-runner-$GEN:generic
